### PR TITLE
Testing travis build status pre-friendship changes

### PR DESCRIPTION
**Pull request by jlblumberg**
Want to see if a new branch with none of the friendship changes will still fail - if so, it's being caused by something local

### CODE REVIEW

**Comment by jlblumberg** [comment]
Build passing before friendship changes. Will commence those now and push often to see which change breaks it.

**Comment by jlblumberg** [comment]
Travis passes post friendship gem installation

**Comment by jlblumberg** [comment]
Travis passes after adding friendships controller

**Comment by jlblumberg** [comment]
Travis failing when adding test for friending. Trying updating webpacker version in gemfile.

**Review by blu3skies — APPROVED** [review]
I approve!

**Pull request merged**
